version: "3.3"
services: 
  pgdatabase: 
    image: postgres:13
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=to_covid
    volumes: 
      - "./to_covid_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin: 
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=elson@elsonlim.com
      - PGADMIN_DEFAULT_PASSWORD=elson
    ports:
      - "8080:80"